- name: Disable UFW
  hosts: all
  become: true
  tasks:
    - name: Stop and disable ufw
      ansible.builtin.service:
        name: ufw
        state: stopped
        enabled: false
      ignore_errors: true

    - name: Disable ufw firewall
      ansible.builtin.command: ufw disable
      changed_when: "'Firewall stopped' in ufw_disable.stdout or 'Firewall is inactive' not in ufw_disable.stdout"
      register: ufw_disable
      ignore_errors: true
