# ansible/k8s_inventory.ini

[servers]
farnsworth ansible_host=192.168.0.X

[agents]
leela ansible_host=192.168.0.Y
bender ansible_host=192.168.0.Z
qbert ansible_host=192.168.0.A

[k3s:children]
servers
agents

[k3s:vars]
ansible_user=jwells
