# ansible/k8s_inventory.ini

[control]
farnsworth ansible_host=192.168.0.253

[workers]
leela ansible_host=192.168.0.95
bender ansible_host=192.168.0.171
qbert ansible_host=192.168.0.170

[k3s:children]
control
workers

[k3s:vars]
ansible_user=jwells
