- name: Install k3s control plane
  ansible.builtin.import_tasks: control.yml
  when: "'control' in group_names"

- name: Install k3s worker
  ansible.builtin.import_tasks: worker.yml
  when: "'workers' in group_names"
